na2mene/web-practice-tech

- pages/_app.tsx
- pages/_document.tsx
- pages/duplicate/index.tsx
- src/app/duplicate/page.tsx
> App RouterとPages Routerで、同じルーティングを指す場合の検証

- src/app/app-router/job_offers/loading.tsx
- 内部的には、 Suspenseを使って実現させている。
- 今後踏まえて、使う使わないも別途検討する必要がありそう
> loading.tsxを使ったスケルトンUIの検証

- package.json
- src/app/app-router/layout.tsx
- src/app/app-router/tanstack/page.tsx
- yarn.lock
- N/A
- cilentで使うものなので、 use clientを仕込むのを忘れず
- ２回レンダリング走るのがよくわかってない
> Tanstack Queryを最小限で導入

- openapi/web-practice-tech/openapi.yaml
- web-api-designs/web-practice-tech/index.yaml
- web-api-designs/web-practice-tech/paths/posts/components/post.yaml
- web-api-designs/web-practice-tech/paths/posts/post__post-id.yaml
- web-api-designs/web-practice-tech/paths/users/components/user.yaml
- web-api-designs/web-practice-tech/paths/users/user.yaml
- web-api-designs/web-practice-tech/paths/users/user__user-id.yaml
- web-api-designs/web-practice-tech/paths/users/user__user-id__comment.yaml
- N/A
- orvalとの紐付きによっては、OpenAPIのルールベースでの制約は必要
> OpenAPIの定義を増やす

- jest.config.ts
- package.json
- src/__mocks__/posts/index.ts
- src/screens/app-router/tanstack/__test__/mockData.ts
- src/screens/app-router/tanstack/__test__/useGetPostList.test.ts
- src/screens/app-router/tanstack/useGetPostList.ts
- yarn.lock
- Must（原則書く）
- Should（書きたいと思ったら程度）
- mockデータの置き場
- 具体的な書き方
> Jestの導入＋Unitテスト（ロジック）

- src/screens/app-router/tanstack/__test__/useGetPostList.test.ts
> テストコードが動くように修正

- src/screens/TanstackScreen/__test__/index.test.tsx
- そもそも書かなくて良さそう
- やるならwaitForで軽くやって、Flakyのときには。。。といった感じか
> jest.mockを使ってインテグレーションをするケースの実装

- src/screens/ApplyScreen/ApplyForm/BasicInformationForm/index.tsx
- src/screens/ApplyScreen/ApplyForm/index.tsx
- src/screens/ApplyScreen/schemas/index.ts
- シンプルなInputは、この実装でコンソールエラーなく完了
- 項目ごとのコンポーネント切り出す作業はまた別のタイミングでやってみる
> 名字、名前、名字かな、名前かなのバリデーション実装

- src/screens/ApplyScreen/ApplyForm/BasicInformationForm/index.tsx
- src/screens/ApplyScreen/ApplyForm/index.tsx
- src/screens/ApplyScreen/schemas/index.ts
- z.enumで定義し、表現してみた
- 問題あれば変更する
- shadcnuiのサンプルコードのように構造を真似した
- defaultValueは、初期値なしなので、undefinedにした
> 性別のバリデーションを実装

- src/screens/ApplyScreen/ApplyForm/BasicInformationForm/index.tsx
- src/screens/ApplyScreen/ApplyForm/index.tsx
- src/screens/ApplyScreen/schemas/index.ts
> 電話番号のバリデーション実装

- src/screens/ApplyScreen/ApplyForm/BasicInformationForm/index.tsx
- src/screens/ApplyScreen/ApplyForm/index.tsx
- src/screens/ApplyScreen/schemas/index.ts
- regex実装
- superRefineで実装
- 厳密にはAPIないのでしていない、ほかと似たような感じになるはずなので無視
- refine系の実行は、全体のすきーまの一般的なバリデーションが完了している後に呼ばれるみたいなので、困るケースが出る
- step形式とかの時に、全体を見られるときつい
- 任意のタイミングでrefine系を実行できる手段を知りたい
- ざっと調べた感じはないっぽい
> メールアドレスバリデーションの実装

- src/screens/ApplyScreen/ApplyForm/BasicInformationForm/index.tsx
- src/screens/ApplyScreen/ApplyForm/index.tsx
- src/screens/ApplyScreen/schemas/index.ts
> パスワードのバリエーション実装

- src/screens/ApplyScreen/ApplyForm/BasicInformationForm/index.tsx
- src/screens/ApplyScreen/ApplyForm/index.tsx
- src/screens/ApplyScreen/schemas/index.ts
- numberの型をベースにして必須チェックが難しかったので、enumで対応
- 何かしらやり方ないのか調べたい
依然として、カスタムバリデーションの実行タイミング問題はある
> 就業状況ステータスのバリデーション実装

- src/components/ui/Select/Birthday/year.tsx
- src/screens/ApplyScreen/ApplyForm/BasicInformationForm/index.tsx
- src/screens/ApplyScreen/ApplyForm/BasicInformationForm/useBasicInformationForm.ts
- Formにまつわるものは、カスタムhooksに切り出す
- useFormContext系
- handler系
- watchしている値など
- YearコンポーネントにstartDateとendDateで拡張性を持たせていたけど、ドメイン知識となるstartとendは、Year側で持つようにした
- hooksで考えたけど、よくよく考えたら、コンポーネント側が持っていればいい
- そもそもデザインコンポーネントで考えると使えないけどそこは改めて検討してもいいかも
- 共通で使えるデザインコンポーネントとは、、、
> 基本情報コンポーネントでの諸々の処理をカスタムhooksに切り出す実装

- src/screens/ApplyScreen/ApplyForm/ApplyInfomationForm/index.tsx
- src/screens/ApplyScreen/ApplyForm/index.tsx
- src/screens/ApplyScreen/schemas/index.ts
- バリデーションそもそもなかったので、コンポーネントだけ実装
- shadcn/uiのSelectの公式の使い方を忠実に再現した
- 後続で、他のSelectも組み直す
> 経験年数のバリデーション実装

- src/screens/ApplyScreen/ApplyForm/ApplyInfomationForm/index.tsx
- src/screens/ApplyScreen/ApplyForm/ApplyInfomationForm/useApplyInformationForm.ts
- src/screens/ApplyScreen/ApplyForm/index.tsx
- src/screens/ApplyScreen/schemas/index.ts
- shadcnサンプル通りにcheckbox実装
- shcemaのrefineのpathを指定しないことでネストさせないように修正
N/A
> 保有資格・免許のバリデーション実装

- src/screens/ApplyScreen/ApplyForm/BasicInformationForm/index.tsx
- src/screens/ApplyScreen/ApplyForm/BasicInformationForm/useBasicInformationForm.ts
- src/screens/ApplyScreen/schemas/index.ts
- refineに定義して、handlerで定義した
- onChange毎にtriggerが発火するので、リクエストが若干気になる
> メールアドレスの重複チェックバリデーションの実装

- src/components/ui/Input/FamilyNameKana/index.tsx
- src/components/ui/Input/FirstName/index.tsx
- src/components/ui/Input/FirstNameKana/index.tsx
- src/screens/ApplyScreen/ApplyForm/BasicInformationForm/index.tsx
- src/screens/ApplyScreen/schemas/index.ts
> 名字かな、名前、名前かなのコンポーネントとスキーマの切り出し

- src/components/ui/Select/Birthday/Day/index.tsx
- src/components/ui/Select/Birthday/Month/index.tsx
- src/components/ui/Select/Birthday/Year/index.tsx
- src/components/ui/Select/Birthday/index.tsx
- src/screens/ApplyScreen/ApplyForm/BasicInformationForm/index.tsx
- src/screens/ApplyScreen/schemas/index.ts
- Birthdayというコンポーネントを作って、Year,Month,Dayはこれまで通りの機能にしている
- UIからみれば、Year等を組み合わせるより生年月日に必要なものを渡すというほうがいいはず
- generate時に、refineのありなしを表現する時に、defaultと全く同じものを書いて解決させてるが、共通でいい感じにできないか？
- エラーメッセージ系が重複しまくっているので、そのオブジェクトを返すみたいなものがあればいいが、いったん目を瞑る
> 生年月日コンポーネントとスキーマの切り出し

- src/components/ui/RadioGroup/Gender/index.tsx
- src/screens/ApplyScreen/ApplyForm/BasicInformationForm/index.tsx
- src/screens/ApplyScreen/schemas/index.ts
> 性別のコンポーネントとスキーマの切り出し

- src/components/ui/Input/Tel/index.tsx
- src/screens/ApplyScreen/ApplyForm/BasicInformationForm/index.tsx
- src/screens/ApplyScreen/schemas/index.ts
> 電話番号のコンポーネントとスキーマの切り出し

- src/components/ui/Input/PostalCode/index.tsx
- src/screens/ApplyScreen/ApplyForm/BasicInformationForm/index.tsx
- src/screens/ApplyScreen/ApplyForm/BasicInformationForm/useBasicInformationForm.ts
- src/screens/ApplyScreen/schemas/index.ts
> 郵便番号のコンポーネントとスキーマの切り出し

- src/screens/ApplyScreen/ApplyForm/BasicInformationForm/useBasicInformationForm.ts
> コードコメントの差し替え

- src/components/ui/Input/Email/index.tsx
- src/screens/ApplyScreen/ApplyForm/BasicInformationForm/index.tsx
- src/screens/ApplyScreen/schemas/index.ts
> メールアドレスのコンポーネントとスキーマの切り出し

- src/components/ui/Input/Password/index.tsx
- src/screens/ApplyScreen/ApplyForm/BasicInformationForm/index.tsx
- src/screens/ApplyScreen/schemas/index.ts
> パスワードのコンポーネントとスキーマの切り出し

- src/components/ui/Select/MemberCareer/Content/index.tsx
- src/components/ui/Select/MemberCareer/index.tsx
- src/screens/ApplyScreen/ApplyForm/ApplyInfomationForm/index.tsx
- src/screens/ApplyScreen/schemas/index.ts
> 経験年数のコンポーネントとスキーマの切り出し

- src/components/ui/Checkbox/Qualifications/index.tsx
- src/screens/ApplyScreen/ApplyForm/ApplyInfomationForm/index.tsx
- src/screens/ApplyScreen/ApplyForm/ApplyInfomationForm/useApplyInformationForm.ts
- src/screens/ApplyScreen/schemas/index.ts
- generate関数の中でrefineをつけるようにすると、defaultValidationの方が命名も自然になると思い変更した。
- この後他のところも直す
> 保有資格・免許のコンポーネントとスキーマの切り出し

- src/components/ui/Select/PreferredDatetime/PreferredTime/index.tsx
- src/components/ui/Select/PreferredDatetime/index.tsx
> 配置周りのスタイルを当てた

- src/components/ui/Select/PreferredDatetime/PreferredDate/index.tsx
- src/components/ui/Select/PreferredDatetime/PreferredTime/index.tsx
- src/components/ui/Select/PreferredDatetime/index.tsx
- src/screens/ApplyScreen/ApplyForm/ApplyInfomationForm/index.tsx
- src/screens/ApplyScreen/ApplyForm/ApplyInfomationForm/useApplyInformationForm.ts
- 相関チェックには、superRefineを使用
- ネストしたネスト先のバリデーションで、複数のエラーをそれぞれの要素にアタッチしたいため
- refineだと、1つに対してtrue/falseでの表現なので、限界がある
- pathの指定を理解したので、birthday周りのグローバルエラーなんとかならないか
> 面接希望日のバリデーションの実装

- src/components/ui/Input/PostalCode/index.tsx
- src/components/ui/Input/Tel/index.tsx
- src/screens/ApplyScreen/ApplyForm/BasicInformationForm/useBasicInformationForm.ts
- どちらも最大長を削除
- 逆にバグとなってしまう
- ハイフンなしの電話番号が13桁いれられてしまうなど
- サニタイズ後の値を使うような修正
> 電話番号と郵便番号のバリデーション一部修正

- src/components/ui/RadioGroup/EmploymentStatus/index.tsx
- src/components/ui/RadioGroup/Gender/index.tsx
- src/screens/ApplyScreen/ApplyForm/BasicInformationForm/index.tsx
- src/screens/ApplyScreen/ApplyForm/BasicInformationForm/useBasicInformationForm.ts
- onBlurだと、1発で反応しないので、onChangeの中でtriggerを使って発火させて対応する
> ラジオボタンコンポーネントのonChangeHandlerを定義

- src/components/ui/Button/QualificationsAcquisitionScheduled/index.tsx
- src/components/ui/Checkbox/MemberQualification/Qualifications/index.tsx
- src/components/ui/Checkbox/MemberQualification/QualificationsAcquisitionScheduled/index.tsx
- src/components/ui/Checkbox/MemberQualification/index.tsx
- src/screens/ApplyScreen/ApplyForm/ApplyInfomationForm/index.tsx
- src/screens/ApplyScreen/ApplyForm/ApplyInfomationForm/useApplyInformationForm.ts
- src/screens/ApplyScreen/ApplyForm/index.tsx
- src/screens/ApplyScreen/schemas/index.ts
- この２つのコンポーネントは、依存し合うバリデーションの相関関係なので、Birthdayと同じようにwrapして相関チェックができるようなコンポーネントにしておく
- refineがだいぶ複雑そうに見えるが、読み解けばやりたいことはシンプル
> 取得予定（1年以内）の 資格・免許の実装と保有資格・免許コンポーネントをWrapする

- src/components/ui/Checkbox/MemberQualification/index.tsx
- ボタンを押下したかどうかのフラグを知る術がだいぶだるいので、取得予定が選択されてなかったらという条件で分岐させた
- あるかないかで、すべてのチェックボックスを含めて再計算する必要があるので、修正
> 保有資格＋取得予定の資格部分をsuperRefineを使って複数同時にバリデーションを発火できるように調整

- src/screens/ApplyScreen/ApplyForm/index.tsx
- handleSubmitに渡す、onErrorの中で、特定の条件の時のみ、エラーをスルーし、onSubmit関数を呼ぶようにした
> 特定の条件の時のみ、資格関係にエラーがあっても、POSTできるようにする実装

- src/components/ui/Checkbox/MemberQualification/Qualifications/index.tsx
- src/components/ui/Checkbox/MemberQualification/QualificationsAcquisitionScheduled/index.tsx
> 資格箇所バリデーションメッセージのline-heightを項目名とあわせた
